exports.Types = {
    normal: "Normal",
    fire: "Fire",
    water: "Water",
    grass: "Grass",
    electric: "Electric",
    ice: "Ice",
    fighting: "Fighting",
    poison: "Poison",
    ground: "Ground",
    flying: "Flying",
    psychic: "Psychic",
    bug: "Bug",
    rock: "Rock",
    ghost: "Ghost",
    dark: "Dark",
    dragon: "Dragon",
    steel: "Steel",
    fairy: "Fairy"
}

exports.Natures = {
    hardy: "Hardy",
    lonely: "Lonely",
    brave: "Brave",
    adamant: "Adamant",
    naughty: "Naughty",
    bold: "Bold",
    docile: "Docile",
    relaxed: "Relaxed",
    impish: "Impish",
    lax: "Lax",
    timid: "Timid",
    hasty: "Hasty",
    serious: "Serious",
    jolly: "Jolly",
    naive: "Naive",
    modest: "Modest",
    mild: "Mild",
    quiet: "Quiet",
    bashful: "Bashful",
    rash: "Rash",
    calm: "Calm",
    gentle: "Gentle",
    sassy: "Sassy",
    careful: "Careful",
    quirky: "Quirky"
}